### ISSUE TITLE
NotificationHandler and ProcessHandler traits should have a 'static bound

### ISSUE THREAD

**Issue by HadrienG2** [RustAudio/rust-jack#105]
...otherwise, the same kind of memory safety issues described in #21 can occur for other implementations of `NotificationHandler` and `ProcessHandler`.

**Comment by wmedrano** [comment]
Correct, will update accordingly and make a release.

**Comment by wmedrano** [comment]
Change is live in 0.6.1

**Comment by HadrienG2** [comment]
Wow, that was quick. Thanks!
