### ISSUE TITLE
Sending from a processHandler into a channel.

### ISSUE THREAD

**Issue by fhennig** [RustAudio/rust-jack#114]
Hi,

I'm new to rust and so this might not be an issue with the library, but I didn't have this issue in a simple example with just threads.

I am trying to read values from an `AudioIn` port, process them and send them into a channel.

This code shows roughly what I want to do:

```rust
extern crate jack;
use jack::{AudioIn, Client, ProcessScope, Control, ClosureProcessHandler, ClientOptions};
use std::sync::mpsc::channel;


pub fn start_processing() {
    // Setup client
    let client = Client::new("rusty_client",
                             ClientOptions::NO_START_SERVER)
        .unwrap().0;

    // Setup port to read
    let spec = AudioIn::default();
    let audio_in_port = client.register_port("in", spec).unwrap();

    // Setup channel
    let (tx, rx) = channel::<f32>();

    let process_handler = ClosureProcessHandler::new(
        move |_: &Client, _process_scope: &ProcessScope| {
            let audio = audio_in_port.as_slice(_process_scope);
            let val = *audio.first().unwrap();
            tx.send(val).unwrap();  // <-- this line breaks it!
            Control::Continue
        });

    let active_client = client.activate_async((), process_handler).unwrap();
}
```

If I try to compile it, it gives me an error:

```
  --> src/minimal.rs:27:32
   |
27 |     let active_client = client.activate_async((), process_handler).unwrap();
   |                                ^^^^^^^^^^^^^^ `std::sync::mpsc::Sender<f32>` cannot be shared between threads safely
   |
   = help: within `jack::ClosureProcessHandler<[closure@src/minimal.rs:20:9: 25:10 audio_in_port:jack::Port<jack::AudioIn>, tx:std::sync::mpsc::Sender<f32>]>`, the trait `std::marker::Sync` is not implemented for `std::sync::mpsc::Sender<f32>`
   = note: required because it appears within the type `[closure@src/minimal.rs:20:9: 25:10 audio_in_port:jack::Port<jack::AudioIn>, tx:std::sync::mpsc::Sender<f32>]`
   = note: required because it appears within the type `jack::ClosureProcessHandler<[closure@src/minimal.rs:20:9: 25:10 audio_in_port:jack::Port<jack::AudioIn>, tx:std::sync::mpsc::Sender<f32>]>`
```

But usually with `move` the `Sender` should be captured and it should be fine! The error implies that I want the sender to be shared, I don't actually want that!

I'm posting this here because in my minimal example with pure rust, I couldn't reproduce the issue. This code is structurally similar, the way I understand the library:

```rust
use std::thread;
use std::sync::mpsc::channel;

fn main() {
    let (tx, rx) = channel::<&str>();

    let handler = move || {
        tx.send("Hey.").unwrap();
    };
    
    thread::spawn(handler);

    let val = rx.recv().unwrap();
    println!("{}", val);
}
```

If someone could point me towards a solution that would be great!

**Comment by wmedrano** [comment]
`Send + Sync` are required because the `JACK` api doesn't really specify much so it was just the safe choice.

As a workaround you can use the crossbeam channel crate which provides Send + Sync channels. Bonus: they are more performant than std's channels. The [sine](https://github.com/RustAudio/rust-jack/blob/master/examples/sine.rs) example makes use of this crate.

**Comment by fhennig** [comment]
Alright, I didn't realize that and didn't know where to check. Thanks for the pointer! I implemented it that way and it works like a charm, thank you very much!
