### ISSUE TITLE
`notification_handler` and `process_handler` should be `mut`?

### ISSUE THREAD

**Issue by xkr47** [RustAudio/rust-jack#118]
Isn't it a bug that `notification_handler` and `process_handler` are not required to be `mut` when passing them to `client.activate_async(...)`? Now I can pass in an immutable instance as e.g. `process_handler` and yet receive it as a `&mut self` in the `process()` callback which means I can mutate the context object.. Example:

```rust
fn main() {
    let context = Context { // not `mut` !
       foo: String::from("orig"),
    };
    let ac = client.activate_async((), context);
    ...
}

struct Context {
    foo: String,
}

impl ProcessHandler for Context {
    fn process(&mut self, client: &Client, ps: &ProcessScope) -> Control {
        self.foo = String::from("new"); // this is fine?
    }
}
```

**Comment by techninja1008** [comment]
@xkr47 This is simply the way rust works. When relating to an owned value (which this case is dealing with - `context` is not a pointer), `mut` is just a marker signalling that the compiler should let you mutate the value, as well as create mutable references of it. As this is just a property of the variable at compile time - and not a property of the value, or a runtime restriction - it is possible to move the value of an immutable variable to a mutable variable and vice versa. You can demonstrate this by adding adding in the following:

```rust
    ...
    let mut context = context;
    let ac = client.activate_async((), context);
    ...
```

**Comment by xkr47** [comment]
Ok sorry for not knowing this and thanks for the great explanation!
