### ISSUE TITLE
Implement Sync on RingBufferWriter

### ISSUE THREAD

**Issue by jimpo** [RustAudio/rust-jack#125]
This may be a bad idea, but is there a reason not to make RingBufferWriter `Sync`? All of its methods require `self` or `&mut self`, so you can't actually do anything with a `RingBufferWriter`. By the same logic, it'd actually be safe to make `RingBuffer` itself `Sync`, though `RingBufferReader` would probably have to be `!Sync` (though that depends on the underlying implementation of `jack_ringbuffer_peak` and `jack_ringbuffer_read_space`).

This would be useful to me as I want my `ProcessHandler` to own a `RingBufferWriter`, and the `ProcessHandler` has to be `Sync` (also see https://github.com/RustAudio/rust-jack/issues/121).

**Comment by Windfisch** [comment]
This indeed is a bad idea. RingBuffer explicitly states "For this to work correctly, there can only be a single reader and a single writer thread. Their identities cannot be interchanged.".
I.e. Neither RingBufferWriter nor -Reader can be `Sync`, only `Send`.

The correct solution would be to require only `Send` but not `Sync` in `ProcessHandler`. This in fact is safe, though not well-documented. See #127 or https://github.com/Windfisch/rust-jack @ 9fa757dc7f8b26f88d4b8f86aec9e6c27717a092 for an implementation of this.
