### ISSUE TITLE
do not unconditionally jack_set_latency_callback, because it overwrites a default handler

### ISSUE THREAD

**Issue by Windfisch** [RustAudio/rust-jack#126]
rust-jack unconditionally calls `jack_set_latency_callback` to register its (default-empty) LatencyCallback. Unfortunately, Jack provides an undocumented, default implementation that does something, which rust-jack is overwriting.
[jack_set_latency_callback](https://github.com/jackaudio/jack2/blob/cd4259d0e8d505480545251bb58e752dbb7deea3/common/JackAPI.cpp#L1033) calls [JackClient::SetLatencyCallback](https://github.com/jackaudio/jack2/blob/cd4259d0e8d505480545251bb58e752dbb7deea3/common/JackClient.cpp#L1189) which sets `fLatency` which [gets called if non-null](https://github.com/jackaudio/jack2/blob/cd4259d0e8d505480545251bb58e752dbb7deea3/common/JackClient.cpp#L433), but [a default implementation is executed when it is null](https://github.com/jackaudio/jack2/blob/cd4259d0e8d505480545251bb58e752dbb7deea3/common/JackClient.cpp#L361)

It seems to basically propagate latencies through the ports.

Possible solutions:
 - rust-jack either should not set that callback (not sure how to implement that)
 - or rust-jack should provide the correct default implementation (and not `{ }`)

**Comment by Windfisch** [comment]
## Impact

Jack offers latency handling assigning every port a "playback" and a "capture" latency. This means for an input port "if you put data into me, it will be delayed 512 frames until it's output on the speakers" and for an output ports "data that's coming out of this port has been seen by a capture device 256 frames ago".

This is useful to know for DAWs and other audio "masters" that play back pre-recorded samples, since they can query and compensate for such latency by using "look-ahead" when playing back and "write-behind" when capturing.

Most "effect processors" (the simplest being a client that just copies data from in to out) should leave the default latency callback in place which just propagates capture latencies from the input to the output ports, and playback latencies from the output to the input ports, in order to not mess with automatic latency compensation.

rust-jack however messes with that default implementation, requiring most effect processors to provide their own implementation to mimic the [default implementation](https://github.com/jackaudio/jack2/blob/cd4259d0e8d505480545251bb58e752dbb7deea3/common/JackClient.cpp#L361).

## Proposed solution

I think the best would consist of the the following steps:
1. re-implement the [default implementation](https://github.com/jackaudio/jack2/blob/cd4259d0e8d505480545251bb58e752dbb7deea3/common/JackClient.cpp#L361) in Rust
2. provide it as `default_latency_for_port()` function of the `NotificationHandler` trait
3. change the default implementation of `latency()` in `NotificationHandler` to call that `default_latency_for_port()` on all ports.

This not only restores default jack behaviour, but even improves it by enabling the user to quickly pass through the values for certain ports (which is a common thing to do, e.g. for monitoring ports) while special-casing other ports.

## Steps to reproduce

- .1. Start jack.
- .2a. Run a `jack_thru` client (or any "official" non-rust jack example client that just copies its input to the output) **OR**
- .2b. Remove the [`latency callback`](https://github.com/RustAudio/rust-jack/blob/41fab12bb08084bb826704de2a90d783f7c70fa5/examples/playback_capture.rs#L136-L144) from [rust-jack/examples/playback_capture.rs](https://github.com/RustAudio/rust-jack/blob/master/examples/playback_capture.rs) and run the modified `playback_capture` example.
- .3. Connect it to `system:playback` and `system:capture`
- .4. Use `jack_lsp -l` to view all ports with their latencies

## Actual Results

The outputs will have the following in common (which signifies the actual hardware latencies):
```
system:capture_1
        port playback latency = [ 0 512 ] frames
        port capture latency = [ 256 256 ] frames
system:capture_2
        port playback latency = [ 0 512 ] frames
        port capture latency = [ 256 256 ] frames
system:playback_1
        port playback latency = [ 512 512 ] frames
        port capture latency = [ 0 256 ] frames
system:playback_2
        port playback latency = [ 512 512 ] frames
        port capture latency = [ 0 256 ] frames
```

for `jack_thru` it will show the following:
```
jack_thru:input_1
        port playback latency = [ 512 512 ] frames
        port capture latency = [ 256 256 ] frames
jack_thru:output_1
        port playback latency = [ 512 512 ] frames
        port capture latency = [ 256 256 ] frames
jack_thru:input_2
        port playback latency = [ 512 512 ] frames
        port capture latency = [ 256 256 ] frames
jack_thru:output_2
        port playback latency = [ 512 512 ] frames
        port capture latency = [ 256 256 ] frames
```
Note how both input ports of `jack_thru` correctly have inherited the capture and playback latencies from the `system:{playback,capture` ports.

For `playback_capture`, however, the following is printed:
```
rust_jack_simple:rust_in_l
        port playback latency = [ 0 0 ] frames
        port capture latency = [ 0 0 ] frames
rust_jack_simple:rust_in_r
        port playback latency = [ 0 0 ] frames
        port capture latency = [ 0 0 ] frames
rust_jack_simple:rust_out_l
        port playback latency = [ 0 0 ] frames
        port capture latency = [ 0 0 ] frames
rust_jack_simple:rust_out_r
        port playback latency = [ 0 0 ] frames
        port capture latency = [ 0 0 ] frames
```

## Expected results

The output from the rust-jack program should have the same numbers as the output for `jack_thru`.

**Comment by Windfisch** [comment]
Considerations about re-implementing the callback in Rust: We would need to keep a list of all ports registered by the client around, so that we can iterate about "all our ports". This would not allow for a zero-cost-abstraction any more.

As an alternative, we could try to find a way to specify a "null" callback in the trait

**Comment by wmedrano** [comment]
Reimplementing sounds good to me. Doing a quick look through Client's discovery methods I don't think there is a way to provide a zero cost reimplementation using jack or even the jack-sys api.

However, is zero cost essential to this? We could provide an OK implementation since if I understand correctly only the ProcessHandler needs to be realtime ready.

**Comment by atoav** [comment]
Could it be that this makes rust-jack in some cases interfere with other jack clients in a bad way? I run mpd via jack and as soon as I start the example `playback_capture`, mpd crashes.

At the risk of being wrong here (this might just be an bug in the way mpd uses jack) mpd writes:
```
Jun 21 18:16 : exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
Jun 21 18:16 : jack_output: Cannot lock down 47664026 byte memory area (Cannot allocate memory)
Jun 21 18:16 : jack_output: Cannot use real-time scheduling (RR/90)(1: Operation not permitted)
Jun 21 18:16 : jack_output: JackClient::AcquireSelfRealTime error
```
I didn't get much else to crash, so it might be really mpd specific.

**Comment by wmedrano** [comment]
I'm closing for now. If setting the latency is something you need, please open a new issue.
