### ISSUE TITLE
Unable to build in Windows 10

### ISSUE THREAD

**Issue by tahnik** [RustAudio/rust-jack#132]
I am trying to build this library as part of `cpal` in Windows 10. I am getting the following error:

```
   Compiling jack-sys v0.2.0
error[E0412]: cannot find type `pthread_t` in crate `libc`
  --> C:\Users\tahni\.cargo\registry\src\github.com-1ecc6299db9ec823\jack-sys-0.2.0\src\lib.rs:16:41
   |
16 | pub type jack_native_thread_t = ::libc::pthread_t;
   |                                         ^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `pthread_t` in crate `libc`
   --> C:\Users\tahni\.cargo\registry\src\github.com-1ecc6299db9ec823\jack-sys-0.2.0\src\lib.rs:222:67
    |
222 |     ::std::option::Option<unsafe extern "C" fn(arg1: *mut ::libc::pthread_t,
    |                                                                   ^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `pthread_attr_t` in crate `libc`
   --> C:\Users\tahni\.cargo\registry\src\github.com-1ecc6299db9ec823\jack-sys-0.2.0\src\lib.rs:223:62
    |
223 | ...                   arg2: *const ::libc::pthread_attr_t,
    |                                            ^^^^^^^^^^^^^^ not found in `libc`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0412`.
error: could not compile `jack-sys`.
```

Is this library supported in Windows?

**Comment by wmedrano** [comment]
Unfortunately I haven't setup my Windows for developing but can do so and look into supporing Windows.

Right now things I need to figure out are:
* What is the supported way for developing in Rust on Windows?
* How do you run JACK on Windows?

**Comment by wmedrano** [comment]
I managed to get the library to compile by omitting pthreads on windows which the JACK headers also do.

After doing this, I managed to run the example after installing JACK from https://jackaudio.org/downloads/

And linking "C:/Program Files/JACK2/lib/libjack".
Since this may only work on my system, will look into what is most often done in windows for this.
