### ISSUE TITLE
buffer_size should likely be in ProcessHandler instead of NotificationHandler

### ISSUE THREAD

**Issue by ollpu** [RustAudio/rust-jack#137]
From the [API docs on `JackBufferSizeCallback`](https://jackaudio.org/api/types_8h.html#aae24422729bb05aa0731a2d9545d278c):

> Prototype for the bufsize_callback that is invoked whenever the JACK engine buffer size changes. Although this function is called in the JACK process thread, the normal process cycle is suspended during its operation, causing a gap in the audio flow. So, the bufsize_callback can allocate storage, touch memory not previously referenced, and perform other operations that are not realtime safe.

This indicates that the `buffer_size` callback is called on the execution thread, but it is allowed to perform blocking operations in this case.

Indeed, with a quick test on JACK2,
```
thread_init called @ ThreadId(2)
sample_rate called @ ThreadId(1)
buffer_size called @ ThreadId(3)
thread_init called @ ThreadId(3)
thread_init called @ ThreadId(4)
process called @ ThreadId(3)
...
```
it seems that the function is called on the execution thread.

`buffer_size` not receiving a reference to the ProcessHandler means that carrying out the kinds of allocations mentioned in the documentation for example becomes needlessly cumbersome. This would be useful in the CPAL implementation which has to reallocate temporary buffers for interleaving.

Am I missing an important detail or would this make sense?

**Comment by wmedrano** [comment]
This makes sense. Feel free to create a PR moving the callback to process or else I can handle it this weekend.

**Comment by ollpu** [comment]
Will do!

**Comment by wmedrano** [comment]
This is live in version `0.7.0`
