### ISSUE TITLE
better documentation for side effects of AsyncClient::drop

### ISSUE THREAD

**Issue by Benjamin-L** [RustAudio/rust-jack#140]
I spent a long time debugging an issue where I didn't keep the result of `activate_client_async` alive, and it was immediately deactivated when the drop impl was run. It would be nice if this was pointed out in the docs somewhere.

**Comment by wmedrano** [comment]
It can probably be annotated with must_use https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute

**Comment by Benjamin-L** [comment]
Yeah, I think that's the way to go. I can make a PR in a bit.
