### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by worikgh** [RustAudio/rust-jack#143]
Dead link: https://rustaudio.github.io/rust-jack/jack/index.html  referred as documentation link from  https://crates.io/crates/jack

**Comment by worikgh** [comment]
https://docs.rs/jack/0.7.1/jack/index.html

**Comment by wmedrano** [comment]
Fixed in https://github.com/RustAudio/rust-jack/commit/614c59bb1796a5f09b1e988a556c587e7e5306f2

**Comment by worikgh** [comment]
The links on crates.io still do not work

**Comment by wmedrano** [comment]
https://crates.io/crates/jack seems fine to me. On the right hand side, I get a link to  docs.rs/jack/0.11.4.

Let me know if it seems fine, but will do a more thorough scrub of crates.io html ~2 weeks when I'm home.

**Comment by worikgh** [comment]
Yep.  Working

I have no idea why it was not last time I tried.
