### ISSUE TITLE
Why is `Client`/`AsyncClient` not `Sync`?

### ISSUE THREAD

**Issue by xlambein** [RustAudio/rust-jack#149]
Hi :-)

I'm working on an application where I need to share an `AsyncClient` between threads.  I tried wrapping it up in an `Arc`, only to realize this wouldn't work because `AsyncClient` is not `Sync`, which `Arc` requires to be `Send`.

From my understanding of JACK, it shouldn't be a problem to share a client pointer between threads, right?  So long as it's only ever closed once.  In fact, this is exactly what we have in the real-time thread.

I think `Client` and `AsyncClient` should be `Sync`, and if there are methods that shouldn't be called by multiple threads at the same time, they should just require `&mut self`.  Am I missing something?

**Comment by wmedrano** [comment]
According to https://jack-devel.jackaudio.narkive.com/NOFlRUhP/jack-functions-thread-safety

JACK is thread-safe, aside from creating a new client. I'll update them to Sync and push a new release.

**Comment by wmedrano** [comment]
This should be live in version `0.8.1`.

**Comment by xlambein** [comment]
Great, thanks! ☺
