### ISSUE TITLE
dynamically load libjack at runtime instead of linking

### ISSUE THREAD

**Issue by Be-ing** [RustAudio/rust-jack#159]
To work around issues of ABI compatibility, particularly on Windows, cross platform C/C++ applications that use JACK typically use a shim that dynamically loads libjack and forwards API calls to the dynamically loaded library. This allows applications to run even if libjack is not available. There are a handful of implementations of this:

https://github.com/x42/weakjack (GPLv2+)
https://github.com/jackaudio/jack2/blob/develop/common/JackWeakAPI.c (LGPL2.1+)
https://github.com/DISTRHO/DPF/blob/develop/distrho/src/jackbridge/JackBridge.hpp (MIT)
https://github.com/juce-framework/JUCE/blob/develop/modules/juce_audio_devices/native/juce_linux_JackAudio.cpp#L26 (ISC)

This could be accomplished by building one of those C shims and statically linking it with jack-sys. Alternatively libloading could be used to do this in Rust. libloading is [already used](https://github.com/RustAudio/rust-jack/blob/main/jack-sys/src/lib.rs#L1077) in jack-sys for `jack_get_cycle_times`.

**Comment by Be-ing** [comment]
Removing the need for having libjack available at build time would also make it easier to build Rust applications, especially on Windows and macOS or cross compiling.

**Comment by Be-ing** [comment]
[dlib](https://lib.rs/crates/dlib) could help with this.

**Comment by wmedrano** [comment]
Thanks for the references, I'll give it a try this weekend. This feature is definitely very value-able when cross compiling.

**Comment by Be-ing** [comment]
> libloading is already used in jack-sys for jack_get_cycle_times.

Getting this to work with dlib could get tricky. However, I think this is unnecessary. Digging into the JACK2 source code, `jack_get_cycle_times` was [added in 2010](https://github.com/jackaudio/jack2/commit/6483c0d5eb354f06af9e39e06b542d4a32ca65a2#diff-eaa8fc369bcefac22c958fd1e0d54e98afc99f8bbaa6108084c3b2875a056636R1330). The declaration in jack.h is marked with the JACK_OPTIONAL_WEAK_EXPORT macro, which is [documented](https://github.com/jackaudio/jack2/blob/37d6369ad3b5a5cc7c84cbb680bfa7f11e67dc44/common/jack/weakjack.h#L24) as existing so applications can use newer JACK API functions and keep the application compatible with old version of JACK. Today, considering the function has existed in JACK2 for 12 years, it is very unlikely anyone will try to use these Rust bindings with a version of libjack so old it does not have `jack_get_cycle_times`, especially considering that Rust being in development wasn't even announced [until the year jack_get_cycle_times was added to JACK2](https://en.wikipedia.org/wiki/Rust_(programming_language)#History).

**Comment by Be-ing** [comment]
My Pinephone Pro just arrived yesterday and I'm looking into how to cross compile Rust from my x86-64 laptop running Linux to the Pinephone Pro. Not having to link a cross-compiled libjack would make this easier.

**Comment by wmedrano** [comment]
Is there any chance you can try the current PR?

```toml
[dependencies]
jack = { git = "https://github.com/RustAudio/rust-jack", branch = "dlib" }
```
