### ISSUE TITLE
Remove special treatment of jack_get_cycle_times

### ISSUE THREAD

**Issue by wmedrano** [RustAudio/rust-jack#163]
jack_get_cycle_times is loaded with libloading. It's possible to remove special treatment and move it into an `external_library!` as well.

Bonus: Add all appropriate configurations in GitHub Actions to test that everything works out fine. Ideally we want to test Linux, Mac, Windows, ARM, x86, Jack 1 & 2, and new JACK versions and old.

**Comment by Be-ing** [comment]
> Bonus: Add all appropriate configurations in GitHub Actions to test that everything works out fine. Ideally we want to test Linux, Mac, Windows, ARM, x86, Jack 1 & 2, and new JACK versions and old.

Chocolatey could be used to install JACK on Windows. Homebrew could be used to install it on macOS.
