### ISSUE TITLE
Who is maintaining this repo/crate? 

### ISSUE THREAD

**Issue by srperens** [RustAudio/rust-jack#191]
Hello! 

I'm just curious as to who is maintaining this repo? Is it only @wmedrano ? Are there other maintainers active here? 

Br, 
Per

**Comment by wmedrano** [comment]
It's mainly me with the occasional contributor.  I mostly contribute in my spare time and work in an entirely unrelated field. Ideally someone with more `JACK` experience would be involved.

**Comment by wmedrano** [comment]
Closing since this is not a technical issue.
