### ISSUE TITLE
callbacks are unsafe due to panicking

### ISSUE THREAD

**Issue by eeeeeta** [RustAudio/rust-jack#41]
Currently, rust-jack does not catch panics at the FFI boundary, resulting in possible unsafety / undefined behaviour.

(c.f. the docs for [std::panic::catch_unwind](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html):)

> It is currently undefined behavior to unwind from Rust code into foreign code, so this function is particularly useful when Rust is called from another language (normally C). This can run arbitrary Rust code, capturing a panic and allowing a graceful handling of the error.

**Comment by HadrienG2** [comment]
In my application, I maintain an AtomicBool that indicates if the audio thread is alive in the shared state between the audio thread and other application threads:

```
    // Check if the audio thread is alive
    fn is_alive(&self) -> bool {
        self.0.alive.load(Ordering::Relaxed)
    }

    // Mark the audio thread as dead
    fn mark_dead(&self) {
        self.0.alive.store(false, Ordering::Relaxed);
    }
```

Then I wrap every JACK audio callback in the following...

```
    fn callback_guard<F>(&self, callback: F) -> Control
        where F: FnMut() -> Control + panic::UnwindSafe
    {
        if !self.is_alive() { return Control::Quit; }
        let result = panic::catch_unwind(callback);
        // FIXME: Store error somewhere so it can be processed
        let output = result.unwrap_or(Control::Quit);
        if output == Control::Quit { self.mark_dead(); }
        output
    }
```

...which ensures the following properties:

- Unhandled panics and Control::Quit returns deactivate the audio thread
- If the JACK callback supports it, JACK is notified by bubbling up a Control::Quit
- If the JACK callback does not support it, then the output can be ignored
- Application can poll is_alive() periodically to check audio thread health

Maybe some variant of this design could be useful to you, and upstreamed as the official solution?

**Comment by wmedrano** [comment]
I ended up implementing HadrienG2's method.
