### ISSUE TITLE
Allocating heap memory in the JACK audio callback ?

### ISSUE THREAD

**Issue by sletz** [RustAudio/rust-jack#70]
I see this kind of code in https://github.com/RustAudio/rust-jack/blob/master/examples/sine.rs example 
```
ClosureProcessHandler::new 
...
let mut out_p = AudioOutPort::new(&mut out_port, ps);
let out: &mut [f32] = &mut out_p;
...
```
but then heap allocation is done in AudioOutPort::new right ? But you're not supposed to do any heap allocation the JACK real-time audio callback... So I'm confused...

**Comment by wmedrano** [comment]
out_p is struct that holds two references (basically pointers).

```rust
pub struct AudioOutPort<'a> {
    _port: &'a mut Port<AudioOutSpec>, // not used, just to borrow Port so that it can't be used anywhere
    buffer: &'a mut [f32], // A slice, this is actually constructed by taking a pointer and length.
}
```

In the case of the buffer, the rust bindings don't allocate any heap memory for the buffer; the slice is actually made from a pointer to some memory that jack has already allocated.

**Comment by sletz** [comment]
Yes... but for the AudioOutPort object itself, allocated with AudioOutPort::new ?

**Comment by wmedrano** [comment]
`AudioOutPort::new` returns a struct which has a known size, not a `Box`. This means that it would be statically allocated like all the variables in the closure.

**Comment by sletz** [comment]
Sorry to ask newbies questions, but what doe that means " would be statically allocated like all the variables in the closure." ? Any reference on that concept ?

**Comment by wmedrano** [comment]
Rust closures are implemented as a struct that holds the captured environment and a function pointer. The function will create out_p as a local variable when called.


Closure implementation
https://doc.rust-lang.org/1.1.0/book/closures.html


If you have a function, and within the function you create a new variable v.
```rust
let v = MyStruct{x: 342.0, y: 30};
```
v would be a local variable on the callstack.
https://en.wikipedia.org/wiki/Call_stack

**Comment by wmedrano** [comment]
edit: perhaps "statically allocated" isn't the right term.

Also note on this implementation.
To activate a client, an object that implements the `ProcessHandler` and `NotificationHandler` need to be passed. I take them, and move them to the heap. I should look into keeping them on the stack or at least have the function take `Box<Handlers>` to make it explicit that these are on the heap.

**Comment by wmedrano** [comment]
Oh, `::new` is not a heap allocation.

**Comment by sletz** [comment]
OK... confused because on C++ habits...
