### ISSUE TITLE
Implement Send for Client and AsyncClient

### ISSUE THREAD

**Issue by Javyre** [RustAudio/rust-jack#71]
When I try to pass the Client instance to another thread, the compiler tells me the Send trait is not satisfied. 

    the trait `std::marker::Send` is not implemented for `*mut jack_sys::Struct__jack_client

Is there a reason for this not being possible? I don't have mutch experience in rust but from what I read, there usually isn't mutch reason to not have Send implemented in most types.

**Comment by wmedrano** [comment]
There's no reason for this, implementing Send sgtm. 🍍

**Comment by Javyre** [comment]
This has been resolved ( #72 )
Closing issue
