### ISSUE TITLE
AudioOutPort::new() should take an immutable reference to port

### ISSUE THREAD

**Issue by bkfox** [RustAudio/rust-jack#88]
`AudioOutPort` (such as other Port wrappers) only uses `Port.buffer(&self)` on the given port. This structure also keeps a mutable reference to it while there is no need for it. (file: src/jack/port/audio.rs:101)

Note: other similar wrapper like `AudioInPort` don't keep mutable references.

Proposal:
* change the mutable reference `_port` in AudioOutPort into an immutable one;
* update the signature of `AudioOutPort::new()` accordingly;

**Comment by wmedrano** [comment]
Will look at this more in detail this weekend, but quick thoughts.

SG as long as you can't get 2 mutable references to the same output buffer.
```rust
let raw_port: Port<AudioOutSpec> ...
let a = AudioOutPort::new(&raw_port);
let b = AudioOutPort::new(&raw_port);
// Does this mean we currently have 2 mutable references to the same buffer?
```

Aside: `_port` probably doesn't need to be a member of AudioInPort

**Comment by wmedrano** [comment]
Obsolete, API changed, accessing data is now done like so:
raw_port.as_mut_slice(ps)
raw_port.as_slice(ps)
