### ISSUE TITLE
midi example not realtime safe?

### ISSUE THREAD

**Issue by x37v** [RustAudio/rust-jack#99]
Am I correct in thinking that the midi example:
https://github.com/RustAudio/rust-jack/blob/48b51f5a3d3df919104d0c7a19b9ff1f0380e7d3/examples/show_midi.rs#L19

uses a process callback?
http://jackaudio.org/files/docs/html/group__ClientCallbacks.html#gafb5ec9fb4b736606d676c135fb97888b
which requires that the callback be realtime safe?

but it prints: https://github.com/RustAudio/rust-jack/blob/48b51f5a3d3df919104d0c7a19b9ff1f0380e7d3/examples/show_midi.rs#L22

which isn't realtime safe I assume.

It not I'll write a variation of it and submit a PR that fixes that for jack best practices.

**Comment by wmedrano** [comment]
Correct, the example was mostly meant to be  something that I can copy paste to get started, but making it realtime safe wouldn't hurt.

**Comment by piegamesde** [comment]
What would be the recommended way to handle prints in the callback? AFAIK, even the example tools in Jack2 do this.

**Comment by x37v** [comment]
> What would be the recommended way to handle prints in the callback? AFAIK, even the example tools in Jack2 do this.

something like https://github.com/RustAudio/rust-jack/pull/113

**Comment by x37v** [comment]
my PR got merged.
